language: python

python:
    - '2.7'
    - '3.3'
    - '3.4'
    - 'pypy'

env:
    - DJANGO="django>=1.4,<1.5"
    - DJANGO="django>=1.5,<1.6"
    - DJANGO="django>=1.6,<1.7"
    - DJANGO="django>=1.7,<1.8"

install:
    - pip install ${DJANGO}
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt

script:
    - python manage.py test

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="django>=1.4,<1.5"
    - python: "3.4"
      env: DJANGO="django>=1.4,<1.5"
