language: python

python:
    - '2.7'
    - '3.3'
    - '3.4'
    - '3.5'
    - '3.6'
    - 'pypy'
    - 'pypy3'

env:
    - DJANGO="django>=1.8,<1.9"
    - DJANGO="django>=1.9,<1.10"
    - DJANGO="django>=1.10,<1.11"
    - DJANGO="django>=1.11,<2"
    - DJANGO="django>=2.0,<2.1"

install:
    - pip install ${DJANGO}
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt

script:
    - python manage.py test

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="django>=2.0,<2.1"
    - python: "pypy"
      env: DJANGO="django>=2.0,<2.1"
    - python: "3.3"
      env: DJANGO="django>=1.9,<1.10"
    - python: "3.3"
      env: DJANGO="django>=1.10,<1.11"
    - python: "3.3"
      env: DJANGO="django>=1.11,<2"
    - python: "3.3"
      env: DJANGO="django>=2.0,<2.1"
    - python: "3.6"
      env: DJANGO="django>=1.8,<1.9"
    - python: "3.6"
      env: DJANGO="django>=1.9,<1.10"
